Bootstrap: docker
From: continuumio/miniconda3:latest
%files
environments/illumina/environment.yml /environment.yml
environments/extras.yml /extras.yml
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%post

apt-get update && apt-get install -y g++ git make procps rsync && apt-get clean -y
/opt/conda/bin/conda update conda
/opt/conda/bin/conda install mamba -c conda-forge
/opt/conda/bin/mamba env create -f /environment.yml
/opt/conda/bin/mamba env update -f /extras.yml -n artic-ncov2019-illumina
/opt/conda/bin/mamba clean -a
PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH

%environment
export PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH
