Bootstrap: docker
From: continuumio/miniconda3:latest
%files
environments/illumina/environment.yml /environment.yml
environments/extras.txt /extras.txt
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%post

apt-get update && apt-get install -y g++ git make procps rsync && apt-get clean -y
/opt/conda/bin/conda env create -f /environment.yml
/opt/conda/envs/artic-ncov2019-illumina/bin/pip install -r /extras.txt && /opt/conda/bin/conda clean -a
PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH

%environment
export PATH=/opt/conda/envs/artic-ncov2019-illumina/bin:$PATH
