Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild
%files
environments/nanopore/environment.yml /environment.yml
environments/extras.yml /extras.yml

%labels
authors="Matt Bull"
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"

%post
/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba env create -f /environment.yml #&& \
/opt/conda/bin/mamba env update -f /extras.yml -n artic

Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update && \
apt-get install -y git procps && \
apt-get clean -y

%files from condabuild
  /opt/conda/envs/artic /opt/conda/envs/artic

%environment
export PATH=/opt/conda/envs/artic/bin:$PATH
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

%runscript
exec "/opt/conda/envs/artic/bin/artic" "$@"
