Bootstrap: docker
From: continuumio/miniconda3:latest
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%files
environments/nanopore/environment.yml /environment.yml
environments/extras.yml /extras.yml
%post

apt-get update && apt-get install -y curl g++ git make procps rsync && apt-get clean -y
/opt/conda/bin/conda update conda
/opt/conda/bin/conda install mamba -c conda-forge
/opt/conda/bin/mamba env create -f /environment.yml
/opt/conda/bin/mamba env update -f /extras.yml -n artic
/opt/conda/bin/mamba clean -a
PATH=/opt/conda/envs/artic/bin:$PATH

%environment
export PATH=/opt/conda/envs/artic/bin:$PATH

%runscript

exec "/opt/conda/envs/artic/bin/artic" "$@"

