Bootstrap: docker
From: continuumio/miniconda3:latest
%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"
%files
environments/extras.yml /extras.yml
%post

apt-get update && apt-get install -y curl g++ git make procps rsync && apt-get clean -y
curl -o /environment.yml -fsSL 'https://raw.githubusercontent.com/artic-network/artic-ncov2019/master/environment.yml' 
/opt/conda/bin/conda env create -f /environment.yml
/opt/conda/bin/conda env update -f /extras.yml -n artic-ncov2019
/opt/conda/bin/conda clean -a
PATH=/opt/conda/envs/artic-ncov2019/bin:$PATH

%environment
export PATH=/opt/conda/envs/artic-ncov2019/bin:$PATH

%runscript

exec "/opt/conda/envs/artic-ncov2019/bin/artic" "$@"

