on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - GHactions_37d2b7a
name: master Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false
    steps:
    - uses: actions/checkout@master
    - name: create artifacts dir to save test logs
      run: mkdir artifacts
    - name: install Singularity
      run: |
       bash .github/scripts/install_singularity.sh
    - name: Build pipeline Singularity containers
      run: |
       echo $(which singularity)
       bash scripts/build_singularity_containers.sh
    - name: install Conda
      run: bash .github/scripts/install_conda.sh
    - name: install Nextflow via Conda
      run: |
       export PATH=/opt/conda/bin:$PATH
       conda install -c bioconda nextflow
       NXF_VER=21.04.0 nextflow -version
    - name: test nanopore pipelines
      run: bash .github/scripts/test_nanopore_pipelines.sh
    - name: test typing functionality
      run: bash .github/scripts/test_typing.sh
    - name: test PR outputs against previous release
      run: bash .github/scripts/test_PR_against_release.sh
    - name: test -profile sanger
      run: bash .github/scripts/test_sanger_profile.sh
    - name: test --cache conda environment 
      run: bash .github/scripts/test_conda_cache.sh
    - name: test --bed and --ref input options 
      run: bash .github/scripts/test_bed_ref_input.sh
    - name: test --cram input together with --bed and --ref
      run: bash .github/scripts/test_cram_input.sh
    - name: test --outCram output together with --cram and --ref
      run: bash .github/scripts/test_cram_output.sh
    - name: if failure, add latest NF log to artifacts
      run: mv .nextflow.log artifacts/failure.nextflow.log
      if: failure()
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test_artifacts
        path: artifacts
